"""initial: job_records

Revision ID: 69c74109651c
Revises: 
Create Date: 2026-09-09 22:48:31.491888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_ref', sa.String(length=512), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_records_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_records_status'), ['status'], unique=False)
        batch_op.create_index('ix_job_records_status_finished', ['status', 'finished_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_records', schema=None) as batch_op:
        batch_op.drop_index('ix_job_records_status_finished')
        batch_op.drop_index(batch_op.f('ix_job_records_status'))
        batch_op.drop_index(batch_op.f('ix_job_records_finished_at'))
        batch_op.drop_index(batch_op.f('ix_job_records_created_at'))

    op.drop_table('job_records')
    # ### end Alembic commands ###
